INCLUDE(FindPackageHandleStandardArgs)
# Look for the header file
if(NOT QTFRAMEWORK_INCLUDE_DIR)
	FIND_PATH(QTFRAMEWORK_INCLUDE_DIR 
	NAMES qfconfig.h
	PATHS ${CMAKE_CURRENT_LIST_DIR}/include/qtframework
	)
	message(${QTFRAMEWORK_INCLUDE_DIR})
endif()
MARK_AS_ADVANCED(QTFRAMEWORK_INCLUDE_DIR)


if(NOT QTFRAMEWORK_LIBRARY)
	FIND_LIBRARY(QTFRAMEWORK_LIBRARY 
	NAMES ${QTFRAMEWORK_LIBRARIES} 
	PATHS ${CMAKE_CURRENT_LIST_DIR}/lib)
	message(${QTFRAMEWORK_LIBRARY})
endif()
MARK_AS_ADVANCED(QTFRAMEWORK_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(QTFRAMEWORK REQUIRED_VARS QTFRAMEWORK_LIBRARY QTFRAMEWORK_INCLUDE_DIR)

IF(QTFRAMEWORK_FOUND)
	message("qtframework found!")
	SET(QTFRAMEWORK_LIBRARIES ${QTFRAMEWORK_LIBRARY})
	SET(QTFRAMEWORK_INCLUDE_DIRS ${QTFRAMEWORK_INCLUDE_DIR})
	include_directories(${QTFRAMEWORK_INCLUDE_DIR})
	link_directories(${QTFRAMEWORK_LIBDIR})
ELSE(QTFRAMEWORK_FOUND)
	message("qtframework notfound!")
	SET(QTFRAMEWORK_LIBRARIES)
	SET(QTFRAMEWORK_LIBRARY)
	SET(QTFRAMEWORK_INCLUDE_DIR)
	SET(QTFRAMEWORK_INCLUDE_DIRS)
ENDIF(QTFRAMEWORK_FOUND)