INCLUDE(FindPackageHandleStandardArgs)
# Look for the header file
if(NOT QFCOMMON_INCLUDE_DIR)
	FIND_PATH(	QFCOMMON_INCLUDE_DIR 
		NAMES qf_common_config.h
		PATHS ${CMAKE_CURRENT_LIST_DIR}/include/qfcommon
	)
	message(${QFCOMMON_INCLUDE_DIR})
endif()
MARK_AS_ADVANCED(QFCOMMON_INCLUDE_DIR)


if(NOT QFCOMMON_LIBRARY)
	FIND_LIBRARY(QFCOMMON_LIBRARY 
	NAMES ${QFCOMMON_LIBRARIES} 
	PATHS ${CMAKE_CURRENT_LIST_DIR}/lib)
	message(${QFCOMMON_LIBRARY})
endif()
MARK_AS_ADVANCED(QFCOMMON_LIBRARY)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(QFCOMMON REQUIRED_VARS QFCOMMON_LIBRARY QFCOMMON_INCLUDE_DIR)

IF(QFCOMMON_FOUND)
	message("qfcommon found!")
	SET(QFCOMMON_LIBRARIES ${QFCOMMON_LIBRARY})
	SET(QFCOMMON_INCLUDE_DIRS ${QFCOMMON_INCLUDE_DIR})
	include_directories(${QFCOMMON_INCLUDE_DIR})
	link_directories(${QFCOMMON_LIBDIR})
ELSE(QFCOMMON_FOUND)
	message("qfcommon notfound!")
	SET(QFCOMMON_LIBRARIES)
	SET(QFCOMMON_LIBRARY)
	SET(QFCOMMON_INCLUDE_DIR)
	SET(QFCOMMON_INCLUDE_DIRS)
ENDIF(QFCOMMON_FOUND)