set(QFMAIN_SRCS
CQF_Main.cpp
CQF_Main.h
IQF_Activator.h
IQF_Command.h
IQF_Component.h
IQF_Main.cpp
IQF_Main.h
IQF_Main_Ext.h
IQF_Message.h
IQF_Observer.h
IQF_Subject.h
IQF_Properties.h
IQF_Property.h
CQF_Properties.h
CQF_Properties.cpp
CQF_Property.h
CQF_Property.cpp
QF_Config.h
qf_config_internal.h
QF_String.cpp
QF_String.h
QF_Subject.cpp
QF_Subject.h	
)

include_directories(${QF_INCLUDE_DIR}/qfmain)
include_directories(${QF_INCLUDE_DIR}/log)

